import {prisma} from "../config/prisma.js";
import {AppError} from "../utils/api.js";
import {categoryConfig,intentStructures,introVariants} from "../data/articleTemplates.js";

export const normalizeTopic=value=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim();
export const slugify=value=>normalizeTopic(value).replace(/[^a-z0-9]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");
const escape=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const hash=value=>[...value].reduce((sum,char)=>(sum*31+char.charCodeAt(0))>>>0,7);
export function detectIntent(topic){const value=normalizeTopic(topic);if(/difference|compar|\bou\b|versus|vs\b/.test(value))return"comparison";if(/routine|etape|etapes/.test(value))return"routine";if(/comment utiliser|application|appliquer|mode d emploi/.test(value))return"usage";if(/comment choisir|quel |quelle |choisir|selection/.test(value))return"selection";return"care";}
const paragraphSets={
  needs:["Commencez par préciser ce que vous attendez de votre routine. Le confort d’utilisation, la texture, le temps disponible et la simplicité des étapes sont des critères concrets. Cette réflexion aide à éviter les achats sans rôle clair et à garder une sélection facile à utiliser au quotidien.","Observez aussi vos habitudes actuelles. Un produit cohérent avec une routine courte sera souvent plus simple à intégrer qu’une étape trop exigeante. Il est possible de commencer avec peu de produits, puis d’ajuster progressivement selon ses préférences et l’expérience d’utilisation."],
  choose:["Comparez les produits à partir des informations réellement disponibles : leur catégorie, leur format, leur description et leur place dans la routine. Une texture légère ou plus enveloppante relève notamment d’une préférence d’usage. Le meilleur repère reste celui qui facilite une utilisation régulière et confortable.","Évitez de changer plusieurs éléments en même temps. En introduisant un choix à la fois, il devient plus facile de comprendre comment il s’intègre dans vos habitudes. Cette méthode garde la routine lisible et permet de prendre une décision sans promesse excessive."],
  routine:["Organisez les étapes dans un ordre simple et mémorisable. Préparez les produits à portée de main et gardez seulement les gestes qui ont une fonction claire. La régularité d’une routine courte est généralement plus facile à maintenir qu’une succession d’étapes difficiles à suivre.","Laissez à votre routine le temps de devenir une habitude avant d’ajouter un nouveau produit. Si une texture ou un format ne vous convient pas, réévaluez ce point sans remplacer toute la sélection. L’objectif est de construire un ensemble cohérent avec votre quotidien."],
  usage:["Lisez les informations fournies avec le produit et respectez son usage prévu. La quantité, la fréquence et le moment d’application peuvent dépendre de sa nature. En cas de doute particulier, demandez l’avis d’un professionnel qualifié plutôt que de multiplier les essais.","Une utilisation attentive passe aussi par des gestes pratiques : refermer les emballages, conserver les produits selon les indications et éviter les associations improvisées. Ces habitudes permettent de garder une routine organisée, sans ajouter de bénéfices ou de propriétés qui ne sont pas documentés."],
  adjust:["Faites régulièrement un point sur la simplicité de la routine. Demandez-vous quelles étapes sont réellement utilisées, lesquelles semblent redondantes et quels formats correspondent à vos préférences. Il est tout à fait possible de simplifier sans recommencer depuis le début.","Les besoins et les habitudes peuvent évoluer avec le temps. Ajustez un élément à la fois et conservez des attentes réalistes. Une routine de soin accompagne le quotidien ; elle ne remplace pas un diagnostic ni un traitement lorsqu’une question médicale se présente."],
};
const blocks=[paragraphSets.needs,paragraphSets.choose,paragraphSets.routine,paragraphSets.usage,paragraphSets.adjust];

async function uniqueSlug(title){const base=slugify(title)||"conseil-skin-by-yas";let candidate=base,index=2;while(await prisma.article.findUnique({where:{slug:candidate},select:{id:true}})){candidate=`${base}-${index++}`;}return candidate;}
async function selectedProducts(productIds){if(!productIds?.length)return[];const unique=[...new Set(productIds)];const products=await prisma.product.findMany({where:{id:{in:unique}},include:{brand:true,category:true},orderBy:{name:"asc"}});if(products.length!==unique.length)throw new AppError(400,"INVALID_PRODUCT_IDS","Un ou plusieurs produits sélectionnés sont introuvables.");return products;}
function productSection(products,heading){if(!products.length)return"";const items=products.map(product=>{const name=escape(product.name),brand=product.brand?.name?` de ${escape(product.brand.name)}`:"",description=product.description?` ${escape(product.description).slice(0,280)}`:"";return `<li>Parmi les produits enregistrés chez Skin by Yas, vous pouvez retrouver <a href="/produits/${escape(product.slug)}"><strong>${name}</strong></a>${brand}.${description}</li>`}).join("");return `<h2>${escape(heading)}</h2><p>Cette sélection présente uniquement des références réelles choisies dans le catalogue. Consultez leur fiche pour retrouver les informations enregistrées par la boutique.</p><ul>${items}</ul>`;}
function titleFor(topic){const trimmed=topic.trim().replace(/\s+/g," ");return trimmed.charAt(0).toUpperCase()+trimmed.slice(1);}
function descriptionFor(title,category){const base=`Découvrez des repères simples autour de « ${title.replace(/[?!]+$/g,"")} » dans l’univers ${category.label} de Skin by Yas.`;return base.length>=140?base.slice(0,157).replace(/\s+\S*$/,"")+"…":`${base} Une approche claire pour organiser votre routine et vos choix.`.slice(0,160);}

export async function generateArticleDraft({topic,category,productIds=[]}){
  const config=categoryConfig[category];if(!config)throw new AppError(400,"INVALID_CATEGORY","Catégorie d’article invalide.");
  const products=await selectedProducts(productIds),intent=detectIntent(topic),structure=intentStructures[intent],title=titleFor(topic),seed=hash(`${normalizeTopic(topic)}:${category}`),intro=introVariants[seed%introVariants.length];
  const headings=[...structure.headings,...config.sections].filter((value,index,array)=>array.indexOf(value)===index).slice(0,6);
  const content=[`<p>${escape(intro)} ${escape(structure.lead)} Cet article propose des repères neutres pour aborder « ${escape(title.replace(/[?!]+$/g,""))} » sans multiplier les étapes ni inventer de promesses.</p>`];
  headings.forEach((heading,index)=>{const paragraphs=blocks[(index+seed)%blocks.length];content.push(`<h2>${escape(heading)}</h2>`,...paragraphs.map(text=>`<p>${escape(text)}</p>`));if(intent==="routine"&&index===1)content.push("<ol><li>Définir l’objectif de chaque étape.</li><li>Choisir un format facile à utiliser.</li><li>Introduire les changements progressivement.</li><li>Observer puis ajuster si nécessaire.</li></ol>");if(intent==="comparison"&&index===1)content.push("<ul><li>Comparer l’usage prévu et la place dans la routine.</li><li>Observer les textures et formats disponibles.</li><li>Choisir selon ses préférences sans supposer de bénéfices non documentés.</li></ul>");});
  if(products.length)content.push(productSection(products,config.productHeading));
  content.push(`<h2>À retenir</h2><p>Gardez une approche simple : clarifiez votre besoin, consultez les informations disponibles et choisissez des produits compatibles avec vos habitudes. Modifiez une étape à la fois et évitez les attentes ou affirmations qui ne figurent pas dans les données vérifiées.</p><p>Avant de finaliser votre sélection, relisez les descriptions enregistrées et vérifiez que chaque produit occupe une place compréhensible dans votre routine. Cette dernière vérification permet de conserver des choix cohérents, de limiter les étapes redondantes et de privilégier une expérience adaptée à vos préférences réelles.</p><p><a href="${config.path}"><strong>${escape(config.cta)}</strong></a></p>`);
  const excerpt=`${intro} ${structure.lead}`.slice(0,220),slug=await uniqueSlug(title),seoTitle=`${title} | Skin by Yas`.slice(0,65),seoDescription=descriptionFor(title,config);
  return{title,slug,excerpt,content:content.join(""),seoTitle,seoDescription,category,relatedProductIds:products.map(product=>product.id),intent};
}
